package com.example.backend.auth.infrastructure.persistence.entity;

import com.example.backend.auth.domain.AccountRole;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;

/** Database representation of an account that may authenticate. */
@Entity
@Table(name = "accounts")
public class AccountEntity {

    /**
     * The stable, non-reassignable identity added by the {@code V2} migration.
     * Generated by the application ({@link com.example.backend.auth.domain.Account}
     * assigns it once, at construction) rather than by the database, so a newly
     * created account has its id before the first {@code INSERT} and every layer
     * above this one already agrees on it.
     */
    @Id
    @Column(nullable = false, updatable = false)
    private UUID id;

    @Column(nullable = false, unique = true)
    private String username;

    /** Nullable: a credentialless account has no hash to store. */
    private String passwordHash;

    @Enumerated(EnumType.STRING)
    private AccountRole role;

    /**
     * Not nullable, so an account that predates the lockout columns reads back as
     * "nothing failed yet" rather than as null and a later increment on it does
     * not have to guess.
     */
    @Column(nullable = false)
    private int failedLoginAttempts;

    /**
     * When the failure run locked the account, and null whenever it is not
     * locked. Never an expiry: a lock is cleared by an administrator's Unlock and
     * by nothing else, so this column is the lock state rather than a deadline to
     * compare a clock against.
     */
    private Instant lockedAt;

    /**
     * Nullable and boxed for that reason: the column was added to a table that
     * already held rows, so a legacy row carries no value. The adapter reads a
     * missing flag as enabled, which is how those rows behaved before the column
     * existed.
     */
    private Boolean enabled;

    /** Nullable for the same reason as {@link #enabled}. */
    private Instant createdAt;

    protected AccountEntity() {
    }

    public AccountEntity(
            UUID id,
            String username,
            String passwordHash,
            AccountRole role,
            int failedLoginAttempts,
            Instant lockedAt,
            Boolean enabled,
            Instant createdAt) {
        this.id = id;
        this.username = username;
        this.passwordHash = passwordHash;
        this.role = role;
        this.failedLoginAttempts = failedLoginAttempts;
        this.lockedAt = lockedAt;
        this.enabled = enabled;
        this.createdAt = createdAt;
    }

    public UUID getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public AccountRole getRole() {
        return role;
    }

    public int getFailedLoginAttempts() {
        return failedLoginAttempts;
    }

    public Instant getLockedAt() {
        return lockedAt;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
